# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 07:01
from __future__ import unicode_literals

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity', models.FloatField(blank=True)),
                ('course', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['time__UTC_time'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UTC_time', models.DateTimeField(db_index=True)),
                ('local_time', models.DateTimeField(blank=True, null=True)),
                ('local_time_zone', timezone_field.fields.TimeZoneField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
