# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 07:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points',
                                    to='tracks.Location'),
        ),
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points',
                                       to='tracks.Time'),
        ),
        migrations.AddField(
            model_name='point',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points',
                                    to='tracks.Track'),
        ),
        migrations.AddField(
            model_name='message',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location',
                                    to='tracks.Location'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time',
                                       to='tracks.Time'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
