# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 23:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tracks', '0002_auto_20170507_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message',
                                       to='tracks.Location'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message',
                                       to='tracks.Time'),
        ),
        migrations.AlterField(
            model_name='point',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point',
                                       to='tracks.Location'),
        ),
        migrations.AlterField(
            model_name='point',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point',
                                       to='tracks.Time'),
        ),
    ]
